version: '3.3'
services:

  backend:
    build: ./backend
    container_name: komodo-portal-backend
    restart: always
    labels:
      - "traefik.frontend.rule=Host:api.komodo-dev.library.illinois.edu"
      - "traefik.backend=komodo_portal_backend"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.port=4040"
    networks:
      - proxy
      - komodo_internal

  frontend:
    build: ./frontend
    container_name: komodo-portal-frontend
    restart: always
    labels:
      - "traefik.frontend.rule=Host:komodo-dev.library.illinois.edu"
      - "traefik.backend=komodo_portal_frontend"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
    environment:
      - VUE_APP_API_BASE_URL 
    networks:
      - proxy
      - komodo_internal

networks:
  proxy:
    external: true
  komodo_internal:
    external: false
