# This Docker (auto) override file creates top-level networks and connects to them in the service level.

# examples of using this file: 
#     $ docker-compose up --build
#     $ docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build

version: '3.3'
services:

  backend:
    labels:
      - "traefik.frontend.rule=Host:api.komodo-dev.library.illinois.edu"
      - "traefik.backend=komodo-portal-backend"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.port=4040"
    networks:
      - proxy
      - komodo_internal

  frontend:
    labels:
      - "traefik.frontend.rule=Host:komodo-dev.library.illinois.edu"
      - "traefik.backend=komodo-portal-frontend"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - komodo_internal

networks:
  proxy:
    external: true
  komodo_internal:
    external: true
