# This Docker (manual) override file opens ports and disables traefik.

# examples of using this file: 
#   DEVELOPMENT ONLY. PROCEED WITH CAUTION, BECAUSE IT WILL OPEN PORTS: 
#     $ docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build frontend
#     $ docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build backend
#     $ docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build 

version: '3.3'
services:

  backend:
    labels:
      - "traefik.enable=false"
    ports:
      - 4040:4040

  frontend:
    labels:
      - "traefik.enable=false"
    ports: 
      - 8080:80
