# This Docker compose file serves as a base. To use it with networks, please see...
# - docker-compose.override.yml
# - docker-compose.dev.yml

# examples of using this file: 
#     $ docker-compose up --build
#     $ docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build

version: '3.3'
services:

  backend:
    build: ./backend
    container_name: komodo-portal-backend
    restart: always

  frontend:
    build: ./frontend
    container_name: komodo-portal-frontend
    restart: always
    environment:
      - VUE_APP_API_BASE_URL 
